spring.application.name=CRUD-Lab

# Conexión a PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/inventario}
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASSWORD:123456}

# Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configuración para ejecutar data.sql después de crear las tablas
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true