apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: crudlab
type: Opaque
stringData:
  DB_URL: "jdbc:postgresql://postgres:5432/inventario"
  DB_USER: "admin"
  DB_PASSWORD: "123456"
